//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Inge_Bases_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificaciones_Cliente
    {
        public string Correo { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> SumaCalificaciones { get; set; }
        public Nullable<int> CantidadResenas { get; set; }
        public Nullable<int> fechaNacimiento { get; set; }
        public Nullable<bool> Bloqueo { get; set; }
    }
}
