//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Inge_Bases_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrasenas_Anteriores
    {
        public string Correo { get; set; }
        public string Contrasena { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
    
        public virtual Registrado Registrado { get; set; }
    }
}
