//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Inge_Bases_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Subastas = new HashSet<Subasta>();
            this.Trueques = new HashSet<Trueque>();
            this.Trueques1 = new HashSet<Trueque>();
            this.Categorias = new HashSet<Categoria>();
            this.Sublistas = new HashSet<Sublista>();
        }
    
        public int ProductoID { get; set; }
        public string CorreoCliente { get; set; }
        public string Nombre { get; set; }
        public double PrecioEstimado { get; set; }
        public string Condicion { get; set; }
        public string Descripcion { get; set; }
        public byte[] ProductoImagen1 { get; set; }
        public byte[] ProductoImagen2 { get; set; }
        public byte[] ProductoImagen3 { get; set; }
        public bool Publicado { get; set; }
        public System.DateTime FechaRegistrado { get; set; }
        public Nullable<System.DateTime> FechaPublicado { get; set; }
        public Nullable<short> Calificacion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public bool Seleccionado { get; set; }
        public short PublicoEspecial { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Fisico Fisico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subasta> Subastas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trueque> Trueques { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trueque> Trueques1 { get; set; }
        public virtual Virtual Virtual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categoria> Categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sublista> Sublistas { get; set; }
    }
}
