//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Inge_Bases_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos_Info_Clientes
    {
        public Nullable<System.DateTime> FechaPublicado { get; set; }
        public string Nombre { get; set; }
        public string CorreoCliente { get; set; }
        public int ProductoID { get; set; }
        public byte[] ProductoImagen1 { get; set; }
        public string Condicion { get; set; }
        public double PrecioEstimado { get; set; }
        public Nullable<byte> CalificacionPromedio { get; set; }
        public string nombre_cliente { get; set; }
    }
}
