//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Inge_Bases_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relacion_ClienteOfertaEnSubasta
    {
        public string CorreoOfertador { get; set; }
        public int ProductoIDSubastado { get; set; }
        public string CorreoSubastador { get; set; }
        public System.DateTime FechaPublicado { get; set; }
        public double PrecioOfrecido { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Subasta Subasta { get; set; }
    }
}
