//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Inge_Bases_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relacion_ClienteTieneInteresCategoria
    {
        public int id { get; set; }
        public string CorreoCliente { get; set; }
        public int IDCategoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
