//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Inge_Bases_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resena
    {
        public string Correo_Cliente_Calificado { get; set; }
        public string Correo_Cliente_Calificador { get; set; }
        public Nullable<byte> Valor { get; set; }
        public System.DateTime Fecha { get; set; }
        public string AtributoNuevo { get; set; }
        public string AtributoNuevo2 { get; set; }
        public string AtributoNuevo3 { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Cliente Cliente1 { get; set; }
    }
}
