//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Inge_Bases_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Generic;
    using System.Configuration;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    using System.Data;
    using System.Data.SqlClient;
    using System.Web.Mvc;
    public partial class Trueque
    {
        public int ProductoIDPublicador { get; set; }
        public string CorreoPublicador { get; set; }
        public int ProductoIDOfertante { get; set; }
        public string CorreoOfertante { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public string Mensaje { get; set; }
        public Nullable<System.DateTime> Finalizado { get; set; }
        public Nullable<short> Calificacion { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Producto Producto1 { get; set; }
        static private string GetConnectionString()
        {
            //El primer string indica la direcci�n del server, esto hay que cambiarlo cuando la base deje de ser local, notese que su utiliza \\ en lugar de \ esto es po un problema de utf-16
            //El segundo es el nombre de la base
            //El tercero maneja las credenciales del usuario que hace la inserci�n, la opci�n que est� ahora es permitida por que es local y  no hay usuarios externos, eso hay que cambiarlo m�s adelante 
            return Properties.Settings.Default.ServerConectionString;
        }

        public string Inserte(int productoIDPublicado, string correoPublicado, int productoIDOfertado, string correoOfertante, DateTime date)
        {
            string connStr = GetConnectionString();
            SqlConnection con = new SqlConnection(connStr);
            SqlCommand getTimeSQLServer = new SqlCommand("SELECT GETDATE() current_date_time", con);
            SqlCommand cmd = new SqlCommand("spTrueque_InsertarTrueque", con);

            cmd.CommandType = CommandType.StoredProcedure;

            cmd.Parameters.Add("@FechaInicio", SqlDbType.DateTime).Value = date;
            cmd.Parameters.Add("@ProductoIDPublicador", SqlDbType.Int).Value = productoIDPublicado;
            cmd.Parameters.Add("@CorreoPublicador", SqlDbType.NVarChar, 50).Value = correoPublicado;
            cmd.Parameters.Add("@ProductoIDOfertante", SqlDbType.Int).Value = productoIDOfertado;
            cmd.Parameters.Add("@CorreoOfertante", SqlDbType.NVarChar, 50).Value = correoOfertante;

            try
            {
                con.Open(); //abre la conexi�n con la base
                cmd.ExecuteNonQuery(); //Ejecuta la consulta
                con.Close(); //Cierra la conexi�n
                return "Success";
            }
            catch (Exception es)
            {
                throw es;
                // Si se usan llaves duplicadas se cae
            }
        }
        public string CreeTrueque(Producto productoPublicado, Producto oferta)
        {
            string connStr = GetConnectionString();
            SqlConnection con = new SqlConnection(connStr);
            SqlCommand cmd = new SqlCommand("Insert into Trueque (ProductoIDPublicador, CorreoPublicador, ProductoIDOfertante, CorreoOfertante, FechaInicio) "
                + "values(@ProductoIDPublicador, @CorreoPublicador, @ProductoIDOfertante, @CorreoOfertante, @FechaInicio)", con);

            SqlCommand getTimeSQLServer = new SqlCommand("SELECT GETDATE() current_date_time", con);
            cmd.Parameters.AddWithValue("@FechaInicio", getTimeSQLServer);
            cmd.Parameters.AddWithValue("@ProductoIDPublicador", productoPublicado.ProductoID);
            cmd.Parameters.AddWithValue("@CorreoPublicador", productoPublicado.CorreoCliente);
            cmd.Parameters.AddWithValue("@ProductoIDOfertante", oferta.ProductoID);
            cmd.Parameters.AddWithValue("@CorreoOfertante", oferta.CorreoCliente);


            try
            {
                con.Open(); //abre la conexi�n con la base
                cmd.ExecuteNonQuery(); //Ejecuta la consulta
                con.Close(); //Cierra la conexi�n
                return "Success";
            }
            catch (Exception es)
            {
                throw es;
            }
        }
    }
}