//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Inge_Bases_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaInteresesCliente
    {
        public string CatCliente { get; set; }
        public int idCliente { get; set; }
        public string CatAmigo { get; set; }
        public int idAmigo { get; set; }
    }
}
